config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'
  devise_for :users
  resources :remarks
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform self}
end

app/models/remark.rb
class Remark < ApplicationRecord
    belongs_to :room
    validates :text, presence: true ,length: { maximum: 500 }
    validates :ip, presence: true
    validates :room_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :remarks, dependent: :destroy
    validates :name, presence: true ,length: { maximum: 20 }
    validates :ip, presence: true
    after_create_commit { RoomBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  before_action :set_remark, only: [:destroy]

  # POST /remark
  def create
    @remark = Remark.new(remark_params)
    @remark.ip = request.remote_ip

    @room = @remark.room

    if @remark.save
      redirect_to @room, notice: 'Remark was successfully created.'
    else
      redirect_to @room, notice: 'Remark creation failed.'
    end

  end

  # DELETE /remarks/1
  def destroy
    @room = @remark.room
    @remark.destroy

    redirect_to @room, notice: 'Comment was successfully destroyed.' 
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_remark
    @remark = Remark.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def remark_params
    params.require(:remark).permit(:text, :room_id)
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @remark = Remark.new
    @remark.room_id = @room.id
    @remarks = @room.remarks 
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.ip = request.remote_ip

    respond_to do |format|
      if @room.save
        format.html { render :new }
        # format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/talkrooms_controller.rb
class TalkroomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/talkrooms_helper.rb
module TalkroomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= render 'rooms/header' %>

    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">チャットアプリ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> 
                </li>
                <li class="nav-item">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> 
                </li>
                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

<% if user_signed_in? %>
    ログインアカウント <strong><%= current_user.email %></strong>.
<% end %>

app/views/rooms/_remark.html.erb
<% remarks.each do |remark| %>
    <div class="text-primary">
        <p><%= remark.ip %> / <%= link_to 'Destroy', remark, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
    <!--吹き出しはじまり-->
    <div class="balloon1">
            <p><%= remark.text %></p>
    </div>
    <!--吹き出し終わり-->
<% end %>

app/views/rooms/_remark_form.html.erb
<%= form_with(model: remark, local: true) do |form| %>
  <% if remark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remark.errors.count, "error") %> prohibited this remark from being saved:</h2>

      <ul>
      <% remark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :remark %>
    <%= form.text_area :text, size: "15x2", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :room_id, value: remark.room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table class='table'>
  <thead class='thead-dark'>
    <tr>
      <th>Name</th>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.ip %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>RoomName:</strong>
  <%= @room.name %>
</p>

<div class="container">
  <%= render 'remark', remarks: @remarks %>
</div>
<hr>
<%= render 'remark_form', remark: @remark %>

<%= link_to 'Back', rooms_path %>

app/views/talkrooms/_message.html.erb
<div calss='message'>
    <p><%= message.content %></p>
</div>

app/views/talkrooms/show.html.erb
<h1>talk room</h1>

<div id='messages'>
    <%= render :partial => 'message', :collection => @messages %>
</div>

<form>
    <label>メッセージを入力</label>
    <input type='text' data-behavior='talkroom_speaker'>
</form>